import os
import warnings
from pathlib import Path
from traitlets import observe


from astropy.coordinates import SkyCoord
from astropy.io import fits
from astropy.wcs import WCS
from astroquery.mast import MastMissions

from regions import (
    PolygonSkyRegion
)

from ipyaladin import Aladin

from mast_table import MastTable
from mast_table.base import mission_mast_ra_dec_colnames

from mast_aladin.aida import AIDA
from mast_aladin.mixins import DelayUntilRendered
import mast_aladin.utils.parquet as parquet
from mast_aladin.utils.validators import is_valid_s3_uri, check_table_for_columns
from mast_aladin.catalogs import (
    PerformanceCatalog,
    ConvexHullRegion,
    is_likely_an_observation_table,
)
from mast_aladin.catalogs.throttle import throttle
import roman_datamodels.datamodels as rdd

__all__ = [
    'MastAladin',
    'gca',
]

# store reference to the latest instantiation:
_latest_instantiated_app = None


class MastAladin(Aladin, DelayUntilRendered, AIDA):
    """
    An Aladin-lite widget with enhanced support for
    datasets from `MAST <https://mast.stsci.edu/>`_, built on
    top of `ipyaladin.widget.Aladin`.
    """
    performance_catalogs = []

    def __init__(self, *args, **kwargs):
        # set ICRSd as the default visible coordinate system
        # in aladin-lite:
        kwargs.setdefault('coo_frame', 'ICRSd')

        super().__init__(*args, **kwargs)

        global _latest_instantiated_app
        _latest_instantiated_app = self

        self.sidecar = kwargs.get("sidecar", None)

    def load_table(
        self,
        table,
        load_footprints=True,
        update_viewport=True,
        unique_column=None
    ):
        table_widget = MastTable(
            table,
            app=self,
            unique_column=unique_column,
            update_viewport=update_viewport
        )

        if load_footprints:
            if 's_region' in table.colnames:
                self.add_graphic_overlay_from_stcs(table['s_region'])
            else:
                raise ValueError(
                    "The table does not contain an `s_region` column, so no "
                    "footprints can be loaded."
                )

        return table_widget

    def add_table(
        self,
        table,
        include_column_names=None,
        shape="cross",
        name=None,
        ra_field=None,
        dec_field=None,
        n_sources_max=5_000,
        performance_cls=ConvexHullRegion,
        **table_options
    ):
        """
        Add ``table`` to mast-aladin. ``table`` may be a source catalog, an observation
        query result table, or a data product query result table.

        If ``table`` is a source catalog, display up to ``n_sources_max`` as scatter points,
        otherwise draw a region representing the convex hull of all source coordinates.

        See `~ipyaladin.widget.Aladin.add_table` for more details on the
        underlying implementation.

        Parameters
        ----------
        table : `~astropy.table.table.QTable` or `~astropy.table.table.Table` or `str`
            The table to add. Valid types are astropy table and S3 URIs of parquet files.

        include_column_names : list[str], optional
            List of column names from the remote parquet table to stream into mast-aladin.

        shape : str | `~ipyaladin.CircleError` | `~ipyaladin.EllipseError`, optional
            The shape to draw for each source. It accepts the strings "square",
            "circle", "plus", "cross", "rhomb", and "triangle" as well as the two
            specific classes `ipyaladin.CircleError` and `ipyaladin.EllipseError`
            that adapt the size of the drawn shapes (circles or ellipses) to error
            columns.
            See ipyaladin example notebook `04_Importing_Tables`.

        name : str, optional
            Name given to the overlay in Aladin.

        ra_field : str, optional
            For source catalog tables, ``ra_field`` is the column name in ``table``
            corresponding to the right ascension of a source. Default is ``"RAJ2000"``,
            which is the name of the RA column generated by CDS for Vizier query responses.

        dec_field : str, optional
            For source catalog tables, ``dec_field`` is the column name in ``table``
            corresponding to the right ascension of a source. Default is ``"DEJ2000"``,
            which is the name of the Dec column generated by CDS for Vizier query responses.

        performance_cls : Subclass of `~mast_aladin.catalogs.performance.PerformanceCatalog`
                          or None, optional
            Options include, for example,
            `~mast_aladin.catalogs.convex_hull_region.ConvexHullRegion` or
            `~mast_aladin.catalogs.priority_column_subset.PriorityColumnSubset`. Use
            `None`, to guarantee that no performance catalog will be constructed for
            this table.

        color : str, function, optional
            The color associated with the catalog. A function can be given similar
            to `shape`.

        source_size : int, float, function, optional
            The size of the sources in the catalog. A function can be given similar
            to `shape`.

        shape : str, function, Image, HTMLCanvasElement, HTMLImageElement, optional
            The shape of the sources (can be, "square", "circle", "plus", "cross", "rhomb",
            "triangle"). If a function is given, user can return Image, HTMLImageCanvas,
            HTMLImageElement or a string being in ["square", "circle", "plus", "cross",
            "rhomb", "triangle"]. This allows to define different shape for a specific
            catalog source.

        limit : int, float, optional
            The maximum number of sources to display.

        on_click : str, function, optional
            Whether the source data appears as a table row or a in popup. Can be
            'showTable' string, 'showPopup' string or a custom user defined
            function that handles the click.

        read_only : bool, optional
            Whether the catalog is read-only.

        filter : function, optional
            The filtering function for sources.

        selection_color : str, optional
            The color to apply to selected sources in the catalog.

        selection_line_width : str, optional
            The line width to apply to selected source footprints in the catalog
            (i.e. the shapes returned by a custom shape function).

        hover_color : str, optional
            The color to apply to sources in the catalog when they are hovered.

        display_label : bool, optional
            Whether to display labels for sources.

        label_column : str, optional
            The name of the column to be used for the label.

        label_color : str, optional
            The color of the source labels.

        label_font : str, optional
            The font for the source labels.

        only_footprints : bool, optional
            When shapes/footprints are associated to a source (through a shape function
            given), decide wheter to show the point source as well. Point source is
            hidden by default

        """
        # handle prefixes to parquet files on S3
        if isinstance(table, (os.PathLike, str)):
            if is_valid_s3_uri(table) and str(table).endswith('.parquet'):
                table = parquet.table_from_s3(table, include_column_names)
            else:
                raise ValueError(
                    f"table='{table}' is not a valid S3 URI for a parquet table."
                )

        # add an already-constructed performance catalog
        if isinstance(table, PerformanceCatalog):
            table._attach_to_mast_aladin(self)
            self.performance_catalogs.append(table)
            return table.overlay_info

        # call `Aladin.add_table` if (1) `performance_cls = None`, (2) the
        # table appears to be an observation query result table (contains an
        # s_region column), (3) n_sources < n_sources_max:
        elif performance_cls is None or (
                (len(table) < n_sources_max or
                 is_likely_an_observation_table(table))):

            # for small source catalogs, or observation tables (not source catalogs),
            # show all sources without performance optimization. Within the PerformanceLayer
            # framework, `performance_cls` is set to `None` in some calls to `add_table`
            # to explicitly avoid the performance behaviors.
            return super().add_table(
                table,
                shape=shape,
                name=name,
                ra_field=ra_field,
                dec_field=dec_field,
                **table_options
            )

        # construct a performance catalog
        else:
            # for large catalogs, show sources within the viewport up to `n_sources_max`;
            # otherwise use `performance_cls` to show an "optimized" vizualization.
            # construct a performance catalog layer:
            if ra_field is None:
                ra_field = "RAJ2000"

            if dec_field is None:
                dec_field = "DEJ2000"

            check_table_for_columns(table, ra_field, dec_field)

            if name is None:
                name = f"Catalog {len(self.performance_catalogs) + 1}"

            catalog_layer = performance_cls(
                table,
                name=name,
                ra_field=ra_field,
                dec_field=dec_field,
                n_sources_max=n_sources_max,
                shape=shape,
                **table_options
            )
            catalog_layer._attach_to_mast_aladin(self)
            self.performance_catalogs.append(catalog_layer)
            return catalog_layer.overlay_info

    @observe('_target', '_rotation', '_fov_xy')
    @throttle(1)
    def _on_viewport_update(self, change):
        # on updates to the viewport center/pan (_target), rotation (_rotation),
        # or the viewport zoom/browser resize/widget aspect ratio (_fov_xy):
        for catalog in self.performance_catalogs:
            catalog._on_viewport_update(change)

    def add_asdf(
        self, asdf, **image_options
    ):
        """Load an ASDF image into the widget.

        Parameters
        ----------
        asdf : Union[str or Path-like, rdd]
            The ASDF image to load in the widget. It can be given as a path (either a
            string or as a `roman_datamodels.datamodels._datamodels.ImageModel`).
        image_options : any
            The options for the image. See the `Aladin Lite image options
            <https://cds-astro.github.io/aladin-lite/global.html#ImageOptions>`_

        """
        if isinstance(asdf, rdd._datamodels.ImageModel):
            asdf_file = asdf
        else:
            asdf_file = rdd.open(asdf)

        wcs_header = fits.Header(asdf_file.meta.wcs.to_fits()[0])

        hdu_list = fits.HDUList(
            [
                fits.PrimaryHDU(header=wcs_header),
                fits.ImageHDU(
                    header=wcs_header,
                    data=asdf_file.data
                )
            ]
        )

        self.add_fits(hdu_list, **image_options)

    def add_fits(
        self, f, extension=1, **image_options
    ):
        """Load a FITS image into the widget.

        Parameters
        ----------
        f : Union[str, Path, HDUList]
            The FITS image to load in the widget. It can be given as a path (either a
            string or a `pathlib.Path` object), or as an `astropy.io.fits.HDUList`.
        extension: int, optional
            FITS extension containing the image data to load. Default is 1.
        image_options : any
            The options for the image. See the `Aladin Lite image options
            <https://cds-astro.github.io/aladin-lite/global.html#ImageOptions>`_

        """

        # Wraps add_fits in ipyaladin to temporarily handle SIP.
        # See ipyaladin for definitions of parameters.

        is_path = isinstance(f, (Path, str))
        if is_path:
            fits_file = fits.open(f)
        else:
            fits_file = f

        if len(fits_file) == 1:
            extension = 0

        data = fits_file[extension].data
        wcs = WCS(fits_file[extension].header)

        if data is None:
            raise ValueError(
                f"No data in extension {extension}."
            )

        wcs.sip = None

        wcs_header = wcs.to_header()

        hdu_list = fits.HDUList(
            [
                fits.PrimaryHDU(header=wcs_header),
                fits.ImageHDU(
                    header=wcs_header,
                    data=data
                )
            ]
        )

        super().add_fits(hdu_list, **image_options)

    def get_viewport_region(self, center=False):
        """Return a `regions.PolygonSkyRegion` representing the perimeter of the
        MastAladin viewport.

        Parameters
        ----------
        center : bool, optional
            If `False` (default), return a region where the vertices are the
            the outer corners of the corner pixels; otherwise the vertices will
            be the corner pixel centers.

        Returns
        -------
        `regions.PolygonSkyRegion`
            Region with vertices representing the corners of the current field
            of view in the viewport.
        """

        sky_corners = SkyCoord(
            self.wcs.calc_footprint(undistort=False, center=center),
            unit='deg'
        )
        return PolygonSkyRegion(sky_corners)

    def search_this_area(
            self,
            mission=None,
            mission_mast=None,
            add_footprints=True,
            name="MAST Search",
            clear_existing=False,
            **query_region_kwargs):
        """`~astroquery.mast.missions.MastMissions`
        Search Missions MAST for observations from ``mission``, and return
        query results in a  `~mast_table.cross_filter_widget.MastTable`.

        Runs a cone search via `~astroquery.mast.MastMissions.query_region` where
        the center coordinate is the center of the viewport, and the radius angle
        is half the length of the viewport's longest dimension.

        Extra keyword arguments are passed to
        `~astroquery.mast.MastMissions.query_region`.

        Users can also provide a pre-configured `~astroquery.mast.missions.MastMissions`
        instance via ``mission_mast``. If both ``mission`` and ``mission_mast``
        are specified, ``mission`` takes precedent.

        Note: the maximum cone search radius supported by
        `~astroquery.mast.missions.MastMissions` is 30 arcmin.

        Parameters
        ----------
        mission : str {'hst', 'jwst', 'roman'}, optional
            Mission to query via Missions Mast. If None, ``mission_mast`` must
            be given.
        mission_mast : `~astroquery.mast.missions.MastMissions`, optional
            User-defined instance of `~astroquery.mast.missions.MastMissions`. If None,
            ``mission`` must be given.
        add_footprints : bool, default True
            Add the query results' observation footprints to Aladin
        name : str, optional
            Name given to footprint overlays in Aladin.
        clear_existing : bool, default False
            If True, footprint overlays from previous calls to ``search_this_area``
            will be removed.
        limit : int
            Default is 5000. The maximum number of dataset IDs in the results.
        offset : int
            Default is 0. The number of records you wish to skip before selecting
            records.
        select_cols: iterable or str or None, optional
            Default is None. Names of columns that will be included in the result
            table. If None, a default set of columns will be returned.
            Can either be an iterable of column names, a comma-separated string
            of column names, or 'all'/'*' to return all available columns.
        count_only : bool, optional
            Default is False. If True, only the count of matching datasets will
            be returned.
        **criteria
            Other mission-specific criteria arguments.
            All valid filters can be found using
            `~astroquery.mast.missions.MastMissionsClass.get_column_list` function.
            For example, one can specify the output columns(select_cols) or use other
            filters(conditions). To filter by multiple values for a single column,
            pass in a list of values or a comma-separated string of values. For the
            Roman mission, you can also use the special "pass_id"

        Returns
        -------
        `~mast_table.cross_filter_widget.MastTable`
            Observation query results.
        """

        if mission is not None and mission_mast is None:
            mission_mast = MastMissions(mission=mission)

        elif mission is None and mission_mast is not None:
            mission = mission_mast.mission.lower()

        elif mission and mission_mast:
            warnings.warn(
                "`search_this_area` was called with values for both `mission` and "
                "`mission_mast`. `mission_mast` takes precedent. `mission` will be "
                "ignored."
            )
            mission = mission_mast.mission.lower()

        else:
            raise ValueError("One of the arguments `mission` or `mission_mast` must be given.")

        if 'coordinates' in query_region_kwargs or 'radius' in query_region_kwargs:
            raise ValueError(
                "`search_this_area` does not accept the MastMissions arguments "
                "`coordinates` or `radius` as keyword arguments. The values for these "
                "arguments are set by `search_this_area` based on the current viewport. "
            )

        coordinates = self.target
        radius = 0.5 * max(self.fov_xy)  # half of the longest side of the viewport

        query_result = mission_mast.query_region(
            coordinates=coordinates,
            radius=radius,
            **query_region_kwargs
        )

        mast_table = MastTable(query_result)

        if add_footprints and len(query_result):
            ra_field, dec_field = mission_mast_ra_dec_colnames[mission]

            if mission == 'jwst':
                dec_field = 'targ_dec'

            if clear_existing and name in self.overlays:
                self.remove_overlay(name)

            overlay = self.add_table(
                query_result,
                name=name,
                ra_field=ra_field,
                dec_field=dec_field,
                only_footprints=True,
            )

            if 's_region' not in query_result.colnames:
                raise ValueError(
                    "Footprints can't be added because the query result "
                    "contains no 's_region' column."
                )

            # store the overlay info on the mast_table
            mast_table.overlay = overlay

            return mast_table

        if len(query_result) == 0:
            # this warning will appear after astroquery.mast's warning that says:
            #  "NoResultsWarning: Query returned no results."
            warnings.warn(
                "`search_this_area` returning None. "
            )
            return None


def gca():
    """
    Get the current mast-aladin application instance.
    If none exist, create a new one.

    Returns
    -------
    `~mast_aladin.app.MastAladin`
    """
    if _latest_instantiated_app is None:
        return MastAladin()

    return _latest_instantiated_app
