import os
from pathlib import Path

from traitlets import List, observe, Instance
from ipywidgets import widget_serialization

from astropy.coordinates import SkyCoord
from astropy.io import fits
from astropy.wcs import WCS
from regions import (
    PolygonSkyRegion
)

from ipyaladin import Aladin

from mast_table import MastTable

from mast_aladin.aida import AIDA
from mast_aladin.mixins import DelayUntilRendered
import mast_aladin.utils.parquet as parquet
from mast_aladin.utils.validators import is_valid_s3_uri
from mast_aladin.catalogs import (
    PerformanceCatalog,
    ConvexHullRegion,
    is_likely_an_observation_table,
)
from mast_aladin.catalogs.throttle import throttle
import roman_datamodels.datamodels as rdd

__all__ = [
    'MastAladin',
    'gca',
]

# store reference to the latest instantiation:
_latest_instantiated_app = None


class MastAladin(Aladin, DelayUntilRendered, AIDA):
    """
    An Aladin-lite widget with enhanced support for
    datasets from `MAST <https://mast.stsci.edu/>`_, built on
    top of `ipyaladin.widget.Aladin`.
    """
    performance_catalogs = List(
        Instance(PerformanceCatalog)
    ).tag(sync=True, **widget_serialization)

    def __init__(self, *args, **kwargs):
        # set ICRSd as the default visible coordinate system
        # in aladin-lite:
        kwargs.setdefault('coo_frame', 'ICRSd')

        super().__init__(*args, **kwargs)

        global _latest_instantiated_app
        _latest_instantiated_app = self

        self.sidecar = kwargs.get("sidecar", None)

    def load_table(
        self,
        table,
        load_footprints=True,
        update_viewport=True,
        unique_column=None
    ):
        table_widget = MastTable(
            table,
            app=self,
            unique_column=unique_column,
            update_viewport=update_viewport
        )

        if load_footprints:
            if 's_region' in table.colnames:
                self.add_graphic_overlay_from_stcs(table['s_region'])
            else:
                raise ValueError(
                    "The table does not contain an `s_region` column, so no "
                    "footprints can be loaded."
                )

        return table_widget

    def add_table(
        self,
        table,
        include_column_names=None,
        shape="cross",
        name=None,
        ra_column=None,
        dec_column=None,
        n_sources_max=5_000,
        performance_cls=ConvexHullRegion,
        **catalog_options
    ):
        """
        Add ``table`` to mast-aladin. ``table`` may be a source catalog, an observation
        query result table, or a data product query result table.

        If ``table`` is a source catalog, display up to ``n_sources_max`` as scatter points,
        otherwise draw a region representing the convex hull of all source coordinates.

        See `~ipyaladin.widget.Aladin.add_table` for more details on the
        underlying implementation.

        Parameters
        ----------
        table : `~astropy.table.table.QTable` or `~astropy.table.table.Table` or `str`
            The table to add. Valid types are astropy table and S3 URIs of parquet files.

        include_column_names : list[str]
            List of column names from the remote parquet table to stream into mast-aladin.

        shape : str | `~ipyaladin.CircleError` | `~ipyaladin.EllipseError`
            The shape to draw for each source. It accepts the strings "square",
            "circle", "plus", "cross", "rhomb", and "triangle" as well as the two
            specific classes `ipyaladin.CircleError` and `ipyaladin.EllipseError`
            that adapt the size of the drawn shapes (circles or ellipses) to error
            columns.
            See ipyaladin example notebook `04_Importing_Tables`.

        name : str
            Name given to the overlay in Aladin.

        ra_column : str
            For source catalog tables, ``ra_column`` is the column name in ``table`` corresponding
            to the right ascension of a source. Default is ``"RAJ2000"``, which is the name of the
            RA column generated by CDS for Vizier query responses.

        dec_column : str
            For source catalog tables, ``dec_column`` is the column name in ``table`` corresponding
            to the right ascension of a source. Default is ``"DEJ2000"``, which is the name of the
            Dec column generated by CDS for Vizier query responses.

        performance_cls : None or subclass of `~mast_aladin.catalogs.catalogs.PerformanceCatalog`
            Options include, for example, `ConvexHullRegionRegion` or `PriorityColumnSubset`. Use
            `None`, to guarantee that no performance catalog will be constructed for this table.

        **catalog_options : dict
            Keyword arguments. The possible values are documented in `Aladin Lite's catalog options
            <https://cds-astro.github.io/aladin-lite/global.html#CatalogOptions>`_.
        """
        # handle prefixes to parquet files on S3
        if isinstance(table, (os.PathLike, str)):
            if is_valid_s3_uri(table) and str(table).endswith('.parquet'):
                table = parquet.table_from_s3(table, include_column_names)
            else:
                raise ValueError(
                    f"table='{table}' is not a valid S3 URI for a parquet table."
                )

        # add an already-constructed performance catalog
        if isinstance(table, PerformanceCatalog):
            table.attach_to_mast_aladin(self)
            self.performance_catalogs.append(table)

        # call `Aladin.add_table` if (1) `performance_cls = None`, (2) the
        # table appears to be an observation query result table (contains an
        # s_region column), (3) n_sources < n_sources_max:
        elif performance_cls is None or (
                (len(table) < n_sources_max or
                 is_likely_an_observation_table(table))):

            # for small source catalogs, or observation tables (not source catalogs),
            # show all sources without performance optimization. Within the PerformanceLayer
            # framework, `performance_cls` is set to `None` in some calls to `add_table`
            # to explicitly avoid the performance behaviors.
            return super().add_table(table, shape=shape, name=name, **catalog_options)

        # construct a performance catalog
        else:
            # for large catalogs, show sources within the viewport up to `n_sources_max`;
            # otherwise use `performance_cls` to show an "optimized" vizualization.
            # construct a performance catalog layer:
            if ra_column is None:
                ra_column = "RAJ2000"

            if dec_column is None:
                dec_column = "DEJ2000"

            if name is None:
                name = f"Catalog {len(self.performance_catalogs) + 1}"

            catalog_layer = performance_cls(
                table,
                name=name,
                ra_column=ra_column,
                dec_column=dec_column,
                n_sources_max=n_sources_max,
                shape=shape,
                **catalog_options
            )
            catalog_layer.attach_to_mast_aladin(self)
            self.performance_catalogs.append(catalog_layer)

    @observe('_target', '_rotation', '_fov_xy')
    @throttle(1)
    def _on_viewport_update(self, change):
        # on updates to the viewport center/pan (_target), rotation (_rotation),
        # or the viewport zoom/browser resize/widget aspect ratio (_fov_xy):
        for catalog in self.performance_catalogs:
            catalog._on_viewport_update(change)

    def add_asdf(
        self, asdf, **image_options
    ):
        """Load an ASDF image into the widget.

        Parameters
        ----------
        asdf : Union[str or Path-like, rdd]
            The ASDF image to load in the widget. It can be given as a path (either a
            string or as a `roman_datamodels.datamodels._datamodels.ImageModel`).
        image_options : any
            The options for the image. See the `Aladin Lite image options
            <https://cds-astro.github.io/aladin-lite/global.html#ImageOptions>`_

        """
        if isinstance(asdf, rdd._datamodels.ImageModel):
            asdf_file = asdf
        else:
            asdf_file = rdd.open(asdf)

        wcs_header = fits.Header(asdf_file.meta.wcs.to_fits()[0])

        hdu_list = fits.HDUList(
            [
                fits.PrimaryHDU(header=wcs_header),
                fits.ImageHDU(
                    header=wcs_header,
                    data=asdf_file.data
                )
            ]
        )

        self.add_fits(hdu_list, **image_options)

    def add_fits(
        self, f, extension=1, **image_options
    ):
        """Load a FITS image into the widget.

        Parameters
        ----------
        f : Union[str, Path, HDUList]
            The FITS image to load in the widget. It can be given as a path (either a
            string or a `pathlib.Path` object), or as an `astropy.io.fits.HDUList`.
        extension: int, optional
            FITS extension containing the image data to load. Default is 1.
        image_options : any
            The options for the image. See the `Aladin Lite image options
            <https://cds-astro.github.io/aladin-lite/global.html#ImageOptions>`_

        """

        # Wraps add_fits in ipyaladin to temporarily handle SIP.
        # See ipyaladin for definitions of parameters.

        is_path = isinstance(f, (Path, str))
        if is_path:
            fits_file = fits.open(f)
        else:
            fits_file = f

        if len(fits_file) == 1:
            extension = 0

        data = fits_file[extension].data
        wcs = WCS(fits_file[extension].header)

        if data is None:
            raise ValueError(
                f"No data in extension {extension}."
            )

        wcs.sip = None

        wcs_header = wcs.to_header()

        hdu_list = fits.HDUList(
            [
                fits.PrimaryHDU(header=wcs_header),
                fits.ImageHDU(
                    header=wcs_header,
                    data=data
                )
            ]
        )

        super().add_fits(hdu_list, **image_options)

    def get_viewport_region(self, center=False):
        """Return a `regions.PolygonSkyRegion` representing the perimeter of the
        MastAladin viewport.

        Parameters
        ----------
        center : bool, optional
            If `False` (default), return a region where the vertices are the
            the outer corners of the corner pixels; otherwise the vertices will
            be the corner pixel centers.

        Returns
        -------
        `regions.PolygonSkyRegion`
            Region with vertices representing the corners of the current field
            of view in the viewport.
        """

        sky_corners = SkyCoord(
            self.wcs.calc_footprint(undistort=False, center=center),
            unit='deg'
        )
        return PolygonSkyRegion(sky_corners)


def gca():
    """
    Get the current mast-aladin application instance.
    If none exist, create a new one.

    Returns
    -------
    `~mast_aladin.app.MastAladin`
    """
    if _latest_instantiated_app is None:
        return MastAladin()

    return _latest_instantiated_app
